### ISSUE TITLE
ilicache ausschalten

### ISSUE THREAD

**Issue by sjib** [claeis/ili2db#132]
How can I influence that an ili is always used from the folder I run ili2pg and does always update the ilicache - e.g. if I am testing and adapting an ili locally. Else my changes of the ili will not be taken into consideration.

**Comment by claeis** [comment]
There is no way to disable the use of $HOME/.ilicache, but you can add the local folder at the head of the ili search path, so that ili2pg finds the locally modified ili file before it starts to search the remote repositories. Something like:
``--modeldir localfolder;%ILI_FROM_DB;%XTF_DIR;http://models.interlis.ch/;%JAR_DIR``
