### ISSUE TITLE
uniform return value

### ISSUE THREAD

**Issue by kuhnpa** [claeis/ili2db#375]
As I try to implement ili2db in a Python-Process, the return value i get by calling ili2db with subprocess is the same, if the tool works fine until the final log entry '...done' or if i run the tool with invalid parameters and it stops before execution.
It would be very helpful, if another return value is given for either 'success', 'failed' and maybe 'errors' for unsuccessful validation.

**Comment by edigonzales** [comment]
Did you have a look here: https://github.com/opengisch/QgisModelBaker/blob/master/QgisModelBaker/libili2db/iliexecutable.py#L129

The plugins runs ili2db also from Python. Seems to read the output from stdout and looks for "...done" with a regexp: https://github.com/opengisch/QgisModelBaker/blob/master/QgisModelBaker/libili2db/iliexecutable.py#L42

@m-kuhn can probably help you on this one.

**Comment by kuhnpa** [comment]
Thanks for the hint. 
I would prefer a proper return value from the application, but as a workaround it would do the job.

**Comment by edigonzales** [comment]
It's still not what you want but if your Python process isn't to complex or requires too exotic frameworks, you can give Jython or graalpython a chance. You can still write Python but import any Java class you want since it is running on a JVM in the end. Using ili2pg is much cleaner since you don't have to deal with system calls or similar stuff.

Some simple examples: https://github.com/edigonzales/ili2db-python

Jython: Implements Python 2.7 but has support for frameworks like Flask or Django.
GraalVM: Implements Python 3.x but lacks support for most frameworks. Numpy and Scipy seem to work.

**Comment by m-kuhn** [comment]
to not get lost, I think it would be good to split the requirements:

- An exit code to get a rough idea if the process was successful or not and avoid parsing `stdout` for `...done` (this issue)
- A feedback channel with a machine readable data stream from ili2pg during runtime, also to avoid parsing
- An API to call specifics of ili2pg

**Comment by claeis** [comment]
will fix it. 

 -   0 ok
 -   !0 failed

**Comment by kuhnpa** [comment]
A distinction of the exit code for a failed call and a successfull call with Errors in the log would be very helpful as well.
