### ISSUE TITLE
support postgresql inheritance

### ISSUE THREAD

**Issue by leader80** [claeis/ili2db#39]
Hi,

is there any tool to create an ili model from SQL code?

Thanks
G.

**Comment by edigonzales** [comment]
Is this even possible? What about all the O/R-mapping logic? The tool would need to know how to deal with INTERLIS structures, associations etc. etc. Since you have today three O/R-mapping rules in ili2pg, how does the tool know which one was applied? 

But perhaps il2pg can be enhanced, it does know its own O/R-mapping.

**Comment by leader80** [comment]
I was thinking something like the pg2ili, basically the reverse procedure that we are currently using to create the schema. 
The cool think about it would be an easier creation of the ili model and much more transparency, it would strongly improve the interlis acceptance between users.

**Comment by edigonzales** [comment]
How does this tool know about e.g. inheritance? There are different strategies how you can to this in relational database.

**Comment by leader80** [comment]
Postgres since version 9,3 supports inheritance as entities structure, so if you use correctly inheritance it will be able to find it.

**Comment by claeis** [comment]
export of any sql schema is out-of-scope

**Comment by leader80** [comment]
wait, is not SQL export, is just inheritance for Postgres

**Comment by leader80** [comment]
hi claude,

does it mean we can use inheritance?

bests
G.
