### ISSUE TITLE
Create SQL script without creating tables in the database

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#85]
It would be nice if `--createscript` can be used to write an sql script without executing the queries in the database at the same time.

**Comment by yesidpol** [comment]
Failed SQL create script in Postgis

ili2pg throw java.lang.NullPointerException in method initDbDefs of class PgSequenceBasedIdGen (DbIdGen) when it calls DbUtility.sequenceExists because conn parameter is null.

createScriptFromIliCoord test successfully passed due to the use of an empty initDbDefs (TableBasedIdGen) implementation.

**Comment by claeis** [comment]
yes (already fixed in cf86dd5 and https://github.com/claeis/ehisqlgen/commit/20cb5aa4d0d476acbc6e5a3330b2b209afd4e371)
